CREATE PROCEDURE Borrowers5BooksPlus AS
SELECT tblBORROWER.Name, tblBORROWER.[Address], COUNT(tblBORROWER.CardNo)
FROM tblBOOK_LOANS FULL OUTER JOIN tblBORROWER
ON tblBOOK_LOANS.CardNo = tblBORROWER.CardNo
GROUP BY tblBORROWER.CardNo, tblBORROWER.Name, tblBORROWER.[Address]
 HAVING COUNT(tblBORROWER.CardNo)  >5
 GO