CREATE PROCEDURE LibraryBranchBooksLoaned AS
SELECT BranchName, COUNT(BookID) FROM
tblLIBRARY_BRANCH FULL OUTER JOIN tblBOOK_LOANS
ON tblLIBRARY_BRANCH.BranchID = tblBOOK_LOANS.BranchID
GROUP BY BranchName
GO